import 'package:flutter/material.dart';

const List<String> staticGenres = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Music',
  'Mystery',
  'Romance',
  'Science Fiction',
  'TV Movie',
  'Thriller',
  'War',
  'Western',
];

final Map<String, IconData> genreIcons = {
  'Action': Icons.flash_on,
  'Adventure': Icons.explore,
  'Animation': Icons.movie_creation,
  'Comedy': Icons.sentiment_very_satisfied,
  'Crime': Icons.local_police,
  'Drama': Icons.theater_comedy,
  'Family': Icons.family_restroom,
  'Fantasy': Icons.auto_stories,
  'History': Icons.history_edu,
  'Horror': Icons.bug_report,
  'Music': Icons.music_note,
  'Mystery': Icons.help_outline,
  'Romance': Icons.favorite,
  'Science Fiction': Icons.rocket_launch,
  'TV Movie': Icons.tv,
  'Thriller': Icons.hearing,
  'War': Icons.military_tech,
  'Western': Icons.sunny,
};

final List<Color> genreColors = [
  Colors.red.shade300,
  Colors.orange.shade300,
  Colors.amber.shade300,
  Colors.yellow.shade300,
  Colors.lime.shade300,
  Colors.lightGreen.shade300,
  Colors.green.shade300,
  Colors.teal.shade300,
  Colors.cyan.shade300,
  Colors.lightBlue.shade300,
  Colors.blue.shade300,
  Colors.indigo.shade300,
  Colors.purple.shade300,
  Colors.deepPurple.shade300,
  Colors.blueGrey.shade300,
  Colors.brown.shade300,
  Colors.grey.shade300,
  Colors.red.shade200,
];
